package interpreterL.parser;

public enum TokenType { // important: SKIP, IDENT, and NUM must have ordinals 1, 2 and 3 
	EOF, SKIP, IDENT, NUM, STRING, STR_CONTENT, PRINT, LET, PLUS, TIMES, EQ, ASSIGN, OPEN_PAR,
	CLOSE_PAR, OPEN_PAIR, CLOSE_PAIR, STMT_SEP, EXP_SEP, OPEN_BLOCK_OR_SET, CLOSE_BLOCK_OR_SET, MINUS, NOT, AND, BOOL,
	IF, ELSE, FST, SND, UNION , INTERSECTION, SIZE, CAT, IN, WHILE
}
